
configurations:
- sealedsecrets.yml

commonLabels:
  app: desktopctl

namespace: desktopctl

configMapGenerator:
- literals:
  - client-id=desktopctl
  - issuer-url=https://login.mtaylor.io
  - redirect-url=https://vms.home.mtaylor.io/auth/callback
  name: oidc

secretGenerator:
- files:
  - ./oidc-secret.json
  name: oidc
  options:
    annotations:
      config.kubernetes.io/local-config: "true"

resources:
- namespace.yml
- deployment.yml
- service.yml
- virtualservice.yml
- rbac.yml
- oidc-secret.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: images.home.mtaylor.io/desktopctl
  newTag: 0.0.1
